### ISSUE TITLE
резолюшн

### ISSUE THREAD

**Issue by Veldergard** [deds129/cub3d-linux_2#3]
https://github.com/deds129/cub3d-linux_2/blob/86ce0394e63695fda3bdfa54e6217bc7a9d25e97/ft_resolution.c#L12
нет проверки на то что уже стоит резолюшн. мб с остальными также

**Comment by deds129** [comment]
там, потом проверяется, да, резолюшн изменится в структуре, но из-за двойного вхождения вылетит ошибка
